import React from 'react';

const Recommendation = ({ icon, resume }) => {
  return (
    <div className='mb-5 shadow-md'>
      <div className='bg-white p-6 rounded-md'>
        <div className='flex gap-2'>
          <div className='text-3xl'>{icon}</div>
          <h1 className='font-semibold text-2xl mb-4'>AI Recommendation</h1>
        </div>
        <p className='text-sm text-gray-500 mb-4'>
          This AI Recommendation is based on your resume. This will generated by
          carefully analyzing your resume.
        </p>
        <div className='flex gap-5 w-full justify-center'>
          <div className='bg-yellow-200 p-6 rounded-lg w-full'>
            <div className='items-center flex flex-col gap-2 '>
              <div className='text-md font-semibold text-yellow-800'>
                {resume.career_guidance}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Recommendation;
